export const dataCostumers = [
  {
    id: "A1",
    name: "Costumers A",
    list: [
      {
        id: "L1",
        email: "deni@gmail.com",
        fullname: "Deni Andreawan",
        phone: "0878",
        address: "Tegal, Indonesia",
      },
      {
        id: "L2",
        email: "tonystark@gmail.com",
        fullname: "Tony Stark",
        phone: "0830",
        address: "New York, USA",
      },
      {
        id: "L3",
        email: "natasyawillona@gmail.com",
        fullname: "Natasya Wilona",
        phone: "0811",
        address: "Jakarta, Indonesia",
      },
      {
        id: "L4",
        email: "brucewayne@gmail.com",
        fullname: "Bruce Wayne",
        phone: "0878",
        address: "Tokyo, Japan",
      },
      {
        id: "L5",
        email: "peterparker@gmail.com",
        fullname: "Peter Parker",
        phone: "0812",
        address: "Yogyakarta, Indonesia",
      },
    ],
  },
  {
    id: "A2",
    name: "Costumers B",
    list: [
      {
        id: "L6",
        email: "bima@gmail.com",
        fullname: "Bima Aji",
        phone: "0811",
        address: "Surabay, Indonesia",
      },
      {
        id: "L7",
        email: "alex@gmail.com",
        fullname: "Alex Jho",
        phone: "0824",
        address: "New York, USA",
      },
      {
        id: "L8",
        email: "yuhu@gmail.com",
        fullname: "Yuhu Wilona",
        phone: "0828",
        address: "Jakarta, Indonesia",
      },
      {
        id: "L9",
        email: "aji@gmail.com",
        fullname: "Aji Wayne",
        phone: "0899",
        address: "Tokyo, Japan",
      },
      {
        id: "L10",
        email: "udo@gmail.com",
        fullname: "Udo Parker",
        phone: "0812",
        address: "Yogyakarta, Indonesia",
      },
    ],
  },
  {
    id: "A3",
    name: "Costumers C",
    list: [
      {
        id: "A11",
        email: "david@gmail.com",
        fullname: "David Andreawan",
        phone: "0878",
        address: "Tegal, Indonesia",
      },
      {
        id: "A12",
        email: "tony@gmail.com",
        fullname: "Tony William",
        phone: "0823",
        address: "New York, USA",
      },
      {
        id: "A13",
        email: "willona@gmail.com",
        fullname: "Wilona Angel",
        phone: "0866",
        address: "Jakarta, Indonesia",
      },
      {
        id: "A14",
        email: "bruce@gmail.com",
        fullname: "Bruce Yudo",
        phone: "0877",
        address: "Tokyo, Japan",
      },
      {
        id: "A15",
        email: "peter12@gmail.com",
        fullname: "Peter Alex",
        phone: "0844",
        address: "Yogyakarta, Indonesia",
      },
    ],
  },
];
